### ISSUE TITLE
Doesn't Seem to Work

### ISSUE THREAD

**Issue by qingxiang-jia** [FirefoxCSSThemers/Monterey-Fox#1]
Hi I saw your theme on "https://firefoxcss-store.github.io/" and is impressed. I tried to copy everything into my "chrome" folder but it doesn't seem to work. I saw two .bat files so I seems to require some extra theme resources. But I am a bit unsure because the theme claims to have been tested on Linux and Mac, but the script is for Windows.

**Comment by rabbithawk256** [comment]
Are you on windows? The install completely breaks firefox (Beta) for me

**Comment by qingxiang-jia** [comment]
I am on Linux

**Comment by alfaaarex** [comment]
> I am on Linux

Hi, The theme works only on Linux. Sorry for the misguiding.

As for Windows, Development is still on.

**Comment by nhermosilla14** [comment]
Maybe you are missing the files from Whitesur. I just noticed you actually need that theme installed first, then this one works fine.
